### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by neuhaus** [RIT-Space-Exploration/SPEXSite#31]
The RSS feed is supposed to be at https://blog.spexcast.com/rss/

However looking at the source code it does NOT look like a valid RSS feed.
My iOS podcast app (podcruncher) is also complaining about the RSS feed.

Please have a look.

Oh and please make new episodes! 💟

**Comment by runphilrun** [comment]
Hi @neuhaus, thanks for bringing this to our attention. We have corrected the issue and you should now find a valid RSS feed at https://blog.spexcast.com/rss/

Please note that the RIT SPEX site in this repository is managed separately from the SPEXcast blog and podcast. Please report future SPEXcast issues directly to our email spexcast@gmail.com. Thanks!

We have a few new podcast episodes in the pipeline :)

- Phil
