### ISSUE TITLE
Add Logo to Upper Corner Link

### ISSUE THREAD

**Issue by venku122** [RIT-Space-Exploration/SPEXSite#4]
http://spex.rit.edu/

**Comment by Beaudidly** [comment]
Would this be to the "SPEX" text link in the upper left? Do we want to the logo to be directly to the left or right of it?

**Comment by venku122** [comment]
I was thinking Logo->"SPEX" with both the logo and Text as an anchor tag
with the attached link. So you could click the text and/or logo and be
redirected.
